// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import oidc.implementation.security.SelfSignedCertificateGenerator;
import oidc.proxies.JWTKeyPair;
import java.io.InputStream;
import java.security.KeyStore;
import java.security.PrivateKey;
import java.security.cert.Certificate;
import java.security.cert.X509Certificate;

public class CreateSelfSignedCertificate extends UserAction<IMendixObject>
{
	/** @deprecated use keyStoreValues.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __keyStoreValues;
	private final oidc.proxies.KeyStore keyStoreValues;

	public CreateSelfSignedCertificate(
		IContext context,
		IMendixObject _keyStoreValues
	)
	{
		super(context);
		this.__keyStoreValues = _keyStoreValues;
		this.keyStoreValues = _keyStoreValues == null ? null : oidc.proxies.KeyStore.initialize(getContext(), _keyStoreValues);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE

        if (this.keyStoreValues == null) {
            throw new MendixRuntimeException("KeyStoreValues is null.");
        }

        final String alias = this.keyStoreValues.getAlias();
        if (alias == null || alias.isBlank()) {
            throw new MendixRuntimeException("KeyStore alias is empty.");
        }

        final String encryptedPassword = this.keyStoreValues.getPassword();
        if (encryptedPassword == null || encryptedPassword.isBlank()) {
            throw new MendixRuntimeException("KeyStore password is empty.");
        }

        final char[] keystorePassword = decryptPassword(encryptedPassword);
        final KeyStore ks = loadKeyStore(keystorePassword);
        final PrivateKey privateKey = extractPrivateKey(ks, alias, keystorePassword);
        final X509Certificate x509Cert = extractX509Certificate(ks, alias);

        return createResult(x509Cert);

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateSelfSignedCertificate";
	}

	// BEGIN EXTRA CODE

    private char[] decryptPassword(String encryptedPassword) {
        try {
            final String keystorePassword = new DecryptString(getContext(), encryptedPassword).executeAction();
            return keystorePassword.toCharArray();
        } catch (Exception e) {
            throw new MendixRuntimeException("Failed to decrypt keystore password", e);
        }
    }

    private KeyStore loadKeyStore(char[] keystorePassword) throws Exception {
        final KeyStore ks = KeyStore.getInstance("JKS");
        try (InputStream is = Core.getFileDocumentContent(getContext(), this.keyStoreValues.getMendixObject())) {
            ks.load(is, keystorePassword);
        }
        return ks;
    }

    private PrivateKey extractPrivateKey(KeyStore ks, String alias, char[] keystorePassword) throws Exception {
        if (!(ks.getKey(alias, keystorePassword) instanceof PrivateKey privateKey)) {
            throw new MendixRuntimeException("Key for alias is not a PrivateKey.");
        }
        return privateKey;
    }

    private X509Certificate extractX509Certificate(KeyStore ks, String alias) throws Exception {
        final Certificate existingCert = ks.getCertificate(alias);
        if (existingCert == null) {
            throw new MendixRuntimeException("Certificate not found in keystore for alias: " + alias);
        }

        if (!(existingCert instanceof X509Certificate x509Cert)) {
            throw new MendixRuntimeException("Certificate is not X509 format");
        }

        return x509Cert;
    }

    private IMendixObject createResult(X509Certificate x509Cert) throws Exception {
        final SelfSignedCertificateGenerator.CertificateHolder certHolder =
                new SelfSignedCertificateGenerator.CertificateHolder(x509Cert);

        final JWTKeyPair result = new JWTKeyPair(getContext());
        result.setCertificate(certHolder.serializeCertificateToPEM());
        result.setThumbprint(certHolder.getCertificateThumbnail());
        result.setExpiresAt(certHolder.getCertificate().getNotAfter());

        return result.getMendixObject();
    }

	// END EXTRA CODE
}
