// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import java.security.InvalidAlgorithmParameterException;
import java.util.Base64;
import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class DecryptString extends UserAction<java.lang.String>
{
	private final java.lang.String value;

	public DecryptString(
		IContext context,
		java.lang.String _value
	)
	{
		super(context);
		this.value = _value;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (this.value == null)
			return null;

		String textPrefix = getPrefix(this.value);
		if (textPrefix == null)
			throw new MendixRuntimeException("Encrypted string does not have a valid prefix.");
		if (!"AES3".equals(textPrefix))
			throw new MendixRuntimeException("Only {AES3} prefix is supported. Found: {" + textPrefix + "}");

		return decryptAes3();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DecryptString";
	}

	// BEGIN EXTRA CODE
	private static final int GCM_TAG_LENGTH = 16; // in bytes
	private static final String PREFIX = "{AES3}";
	private static final Pattern PREFIX_REGEX = Pattern.compile("^\\{([a-zA-Z0-9]*)\\}.*$");
	private static final String WRONG_KEY_ERROR_MESSAGE = "Cannot decrypt the text because it was either encrypted with a different key or not encrypted at all";
	private static final String KEY_CONSTANT = "OIDC.EncryptionKey";

	private String resolveKey() {
		String key = (String) Core.getConfiguration().getConstantValue(KEY_CONSTANT);
		if (key == null || key.isEmpty())
			throw new MendixRuntimeException("Encryption key is not configured. Set a 32-character key in the constant '" + KEY_CONSTANT + "'.");
		if (key.length() != 32)
			throw new MendixRuntimeException("Encryption key must be exactly 32 characters (AES-256).");
		return key;
	}

	private String decryptAes3() throws Exception {
		String key = resolveKey();

		String[] s = this.value.substring(PREFIX.length()).split(";");
		if (s.length < 2)
			throw new MendixRuntimeException("Unexpected format when trying to decrypt string.");

		Cipher c = Cipher.getInstance("AES/GCM/NoPadding");
		SecretKeySpec k = new SecretKeySpec(key.getBytes(), "AES");

		byte[] iv = Base64.getDecoder().decode(s[0].getBytes());
		byte[] encryptedData = Base64.getDecoder().decode(s[1].getBytes());

		try {
			GCMParameterSpec spec = new GCMParameterSpec(GCM_TAG_LENGTH * 8, iv);
			c.init(Cipher.DECRYPT_MODE, k, spec);
			return new String(c.doFinal(encryptedData));
		} catch (InvalidAlgorithmParameterException | BadPaddingException ex) {
			if (isEncryptedWithWrongKey(ex.getMessage()))
				throw new MendixRuntimeException(WRONG_KEY_ERROR_MESSAGE);
			else throw ex;
		}
	}

	private boolean isEncryptedWithWrongKey(String message) {
		return message.contains("Wrong IV length") ||
				message.contains("Given final block not properly padded") ||
				message.contains("Tag mismatch");
	}

	private String getPrefix(String text) {
		Matcher m = PREFIX_REGEX.matcher(text);
		return m.find() ? m.group(1) : null;
	}
	// END EXTRA CODE
}
