// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class EncryptString extends UserAction<java.lang.String>
{
	private final java.lang.String value;

	public EncryptString(
		IContext context,
		java.lang.String _value
	)
	{
		super(context);
		this.value = _value;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (this.value == null)
			return null;

		String key = resolveKey();

		Cipher c = Cipher.getInstance("AES/GCM/NoPadding");
		SecretKeySpec k = new SecretKeySpec(key.getBytes(), "AES");
		c.init(Cipher.ENCRYPT_MODE, k);

		byte[] encryptedData = c.doFinal(this.value.getBytes());
		byte[] iv = c.getIV();

		StringBuilder sb = new StringBuilder(PREFIX);
		sb.append(new String(Base64.getEncoder().encode(iv)));
		sb.append(';');
		sb.append(new String(Base64.getEncoder().encode(encryptedData)));
		return sb.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "EncryptString";
	}

	// BEGIN EXTRA CODE
	private static final String PREFIX = "{AES3}";
	private static final String KEY_CONSTANT = "OIDC.EncryptionKey";

	private String resolveKey() {
		String key = (String) Core.getConfiguration().getConstantValue(KEY_CONSTANT);
		if (key == null || key.isEmpty())
			throw new MendixRuntimeException("Encryption key is not configured. Set a 32-character key in the constant '" + KEY_CONSTANT + "'.");
		if (key.length() != 32)
			throw new MendixRuntimeException("Encryption key must be exactly 32 characters (AES-256).");
		return key;
	}
	// END EXTRA CODE
}
