// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.mendix.systemwideinterfaces.MendixRuntimeException;
import oidc.implementation.common.HexToBinaryConverter;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.nimbusds.jose.JOSEObjectType;
import com.nimbusds.jose.JWSAlgorithm;
import com.nimbusds.jose.JWSHeader;
import com.nimbusds.jose.crypto.RSASSASigner;
import com.nimbusds.jose.util.Base64URL;
import com.nimbusds.jwt.JWTClaimsSet;
import com.nimbusds.jwt.SignedJWT;
import oidc.implementation.common.Constants;
import oidc.proxies.Audience;
import oidc.proxies.Audience.MemberNames;
import java.io.InputStream;
import java.security.Key;
import java.security.KeyStore;
import java.security.PrivateKey;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import com.nimbusds.jose.util.Base64;

public class GenerateSignedJWTAssertion extends UserAction<java.lang.String>
{
	/** @deprecated use clientConfiguration.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __clientConfiguration;
	private final oidc.proxies.ClientConfiguration clientConfiguration;
	/** @deprecated use JWT.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __JWT;
	private final oidc.proxies.JWT JWT;
	/** @deprecated use keyStore.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __keyStore;
	private final oidc.proxies.KeyStore keyStore;
	/** @deprecated use jwtKeyPair.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __jwtKeyPair;
	private final oidc.proxies.JWTKeyPair jwtKeyPair;

	public GenerateSignedJWTAssertion(
		IContext context,
		IMendixObject _clientConfiguration,
		IMendixObject _jWT,
		IMendixObject _keyStore,
		IMendixObject _jwtKeyPair
	)
	{
		super(context);
		this.__clientConfiguration = _clientConfiguration;
		this.clientConfiguration = _clientConfiguration == null ? null : oidc.proxies.ClientConfiguration.initialize(getContext(), _clientConfiguration);
		this.__JWT = _jWT;
		this.JWT = _jWT == null ? null : oidc.proxies.JWT.initialize(getContext(), _jWT);
		this.__keyStore = _keyStore;
		this.keyStore = _keyStore == null ? null : oidc.proxies.KeyStore.initialize(getContext(), _keyStore);
		this.__jwtKeyPair = _jwtKeyPair;
		this.jwtKeyPair = _jwtKeyPair == null ? null : oidc.proxies.JWTKeyPair.initialize(getContext(), _jwtKeyPair);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        final IContext ctx = getContext();
        final ILogNode logger = Core.getLogger(Constants.LOG_NODE);

        validateInputs();

        final JWSAlgorithm signingAlgorithm = JWSAlgorithm.RS256;

        final String keystorePwd = decryptKeystorePassword(ctx);

        // Load keystore and extract private key
        final KeyStore javaKeyStore = loadKeystore(keystorePwd);
        final PrivateKey signingKey = extractPrivateKey(javaKeyStore, keystorePwd);

        var certificateThumbprint = Base64.encode(HexToBinaryConverter.hexStringToByteArray(jwtKeyPair.getThumbprint())).toString();

        final JWSHeader jwtHeader = buildHeaderWithThumbprint(signingAlgorithm, new Base64URL(certificateThumbprint));
        final JWTClaimsSet jwtClaims = buildClaimsSet(ctx);
        final String signedToken = signAndSerializeJWT(jwtHeader, jwtClaims, signingKey);

        logger.info("Certificate-based JWT generated successfully with RS256");
        return signedToken;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateSignedJWTAssertion";
	}

	// BEGIN EXTRA CODE
    private void validateInputs() {
        if (keyStore == null) {
            throw new MendixRuntimeException("KeyStore cannot be null");
        }
        if (JWT == null) {
            throw new MendixRuntimeException("JWT cannot be null");
        }
        if (jwtKeyPair == null) {
            throw new MendixRuntimeException("JWTKeyPair cannot be null");
        }
        if (keyStore.getAlias() == null || keyStore.getAlias().isBlank()) {
            throw new MendixRuntimeException("KeyStore alias is required");
        }
        if (jwtKeyPair.getThumbprint() == null || jwtKeyPair.getThumbprint().isBlank()) {
            throw new MendixRuntimeException("JWTKeyPair thumbprint is required");
        }
    }

    private String decryptKeystorePassword(IContext ctx) {
        final String encryptedPwd = keyStore.getPassword();
        if (encryptedPwd == null || encryptedPwd.isBlank()) {
            throw new MendixRuntimeException("KeyStore password is empty");
        }

        final String decryptedPwd;
        try {
            decryptedPwd = new DecryptString(ctx, encryptedPwd).executeAction();
        } catch (Exception e) {
            throw new MendixRuntimeException("Failed to decrypt keystore password: " + e.getMessage(), e);
        }

        if (decryptedPwd == null || decryptedPwd.isBlank()) {
            throw new MendixRuntimeException("Failed to decrypt keystore password");
        }

        return decryptedPwd;
    }

    private KeyStore loadKeystore(String password) throws Exception {
        final KeyStore ks = KeyStore.getInstance("JKS");
        try (InputStream inputStream = Core.getFileDocumentContent(getContext(), keyStore.getMendixObject())) {
            if (inputStream == null) {
                throw new MendixRuntimeException("KeyStore file content is null");
            }
            ks.load(inputStream, password.toCharArray());
        }
        return ks;
    }

    private PrivateKey extractPrivateKey(KeyStore ks, String password) throws Exception {
        final String alias = keyStore.getAlias();
        final Key extractedKey = ks.getKey(alias, password.toCharArray());

        if (extractedKey == null) {
            throw new MendixRuntimeException("No key found for alias: " + alias);
        }
        if (!(extractedKey instanceof PrivateKey)) {
            throw new MendixRuntimeException("Key for alias '" + alias + "' is not a PrivateKey");
        }

        return (PrivateKey) extractedKey;
    }

    private JWSHeader buildHeaderWithThumbprint(JWSAlgorithm algorithm, Base64URL thumbprint) {
        return new JWSHeader.Builder(algorithm)
                .type(JOSEObjectType.JWT)
                .x509CertThumbprint(thumbprint)
                .build();
    }

    private JWTClaimsSet buildClaimsSet(IContext ctx) {
        final Date currentTime = new Date();
        final Date expirationTime = JWT.getexp();

        if (expirationTime == null) {
            throw new MendixRuntimeException("JWT expiration time (exp) cannot be null");
        }

        // Retrieve audiences
        final List<IMendixObject> audienceObjects = Core.retrieveByPath(
                ctx,
                JWT.getMendixObject(),
                MemberNames.Audience_JWT.toString()
        );

        final List<String> audienceList = new ArrayList<>();
        for (IMendixObject audObj : audienceObjects) {
            Audience aud = Audience.initialize(ctx, audObj);
            audienceList.add(aud.getaud());
        }

        JWTClaimsSet.Builder claimsBuilder = new JWTClaimsSet.Builder()
                .issuer(JWT.getiss())
                .subject(JWT.getsub())
                .expirationTime(expirationTime)
                .issueTime(currentTime)
                .notBeforeTime(currentTime)
                .jwtID(JWT.getjti());

        if (!audienceList.isEmpty()) {
            claimsBuilder.audience(audienceList);
        }

        return claimsBuilder.build();
    }

    private String signAndSerializeJWT(JWSHeader header, JWTClaimsSet claims, PrivateKey privateKey) throws Exception {
        final SignedJWT signedJWT = new SignedJWT(header, claims);
        final RSASSASigner rsaSigner = new RSASSASigner(privateKey);
        signedJWT.sign(rsaSigner);
        return signedJWT.serialize();
    }
	// END EXTRA CODE
}
