// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.m2ee.api.IMxRuntimeRequest;
import java.util.Optional;
import static oidc.implementation.common.URLUtils.*;

public class GetApplicationUrlFromRequest extends UserAction<java.lang.String>
{
	public GetApplicationUrlFromRequest(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        Optional<IMxRuntimeRequest> requestOptional = getContext().getRuntimeRequest();
        if (requestOptional.isPresent()) {
            return removeTrailingSlash(getApplicationUrlFromRequest(requestOptional.get()));
        }
        return removeTrailingSlash(getDefaultAppRootUrl());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetApplicationUrlFromRequest";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
