// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.m2ee.api.IMxRuntimeRequest;
import com.mendix.m2ee.api.IMxRuntimeResponse;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import io.netty.handler.codec.http.cookie.CookieHeaderNames;
import javax.servlet.http.HttpServletResponse;
import java.util.Optional;
import static oidc.implementation.CookieUtil.*;
import static oidc.implementation.common.URLUtils.*;

public class UnSetNonceCookie extends UserAction<java.lang.Void>
{
	private final java.lang.String state;

	public UnSetNonceCookie(
		IContext context,
		java.lang.String _state
	)
	{
		super(context);
		this.state = _state;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		Optional<IMxRuntimeRequest> requestOptional = getContext().getRuntimeRequest();
		Optional<IMxRuntimeResponse> responseOptional = getContext().getRuntimeResponse();
		if(requestOptional.isEmpty())
			throw new MendixRuntimeException("RuntimeRequest must not be null");

		if(responseOptional.isEmpty())
			throw new MendixRuntimeException("RuntimeResponse must not be null");

		IMxRuntimeRequest request= requestOptional.get();
		IMxRuntimeResponse response= responseOptional.get();
		unsetNonceCookie(request, response, state);

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "UnSetNonceCookie";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
